title: CCU Project Website — Team 16
description: A website for storing documents made for User-Centered Design and Evaluation course
theme: just-the-docs

url: https://hirvonensara.github.io/CCU_project

aux_links:
  Template Repository: https://github.com/hirvonensara/CCU_project
